### ISSUE TITLE
error Item (Mage_Sales_Model_Order) with the same id "XX" already exist

### ISSUE THREAD

**Issue by roman204** [wirecard/magento-ee#78]
when a customer tries to pay with sofortbanking the following error appears and cart gets cleared
```
a:5:{i:0;s:67:"Item (Mage_Sales_Model_Order) with the same id "9889" already exist";i:1;s:1862:"#0 /var/www/production/releases/20191007061419/htdocs/lib/Varien/Data/Collection/Db.php(582): Varien_Data_Collection->addItem(Object(Mage_Sales_Model_Order))
#1 /var/www/production/releases/20191007061419/htdocs/lib/Varien/Data/Collection.php(752): Varien_Data_Collection_Db->load()
#2 /var/www/production/releases/20191007061419/htdocs/app/code/community/WirecardEE/PaymentGateway/Helper/Threeds.php(206): Varien_Data_Collection->count()
#3 /var/www/production/releases/20191007061419/htdocs/app/code/community/WirecardEE/PaymentGateway/controllers/GatewayController.php(228): WirecardEE_PaymentGateway_Helper_Threeds->hasReorderedItems(Object(Mage_Sales_Model_Order))
#4 /var/www/production/releases/20191007061419/htdocs/app/code/community/WirecardEE/PaymentGateway/controllers/GatewayController.php(64): WirecardEE_PaymentGateway_GatewayController->buildOrderSummary(Object(Mage_Sales_Model_Order), Object(WirecardEE\PaymentGateway\Payments\SofortPayment))
#5 /var/www/production/releases/20191007061419/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): WirecardEE_PaymentGateway_GatewayController->indexAction()
#6 /var/www/production/releases/20191007061419/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#7 /var/www/production/releases/20191007061419/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /var/www/production/releases/20191007061419/htdocs/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#9 /var/www/production/releases/20191007061419/htdocs/app/Mage.php(694): Mage_Core_Model_App->run(Array)
#10 /var/www/production/releases/20190725153855/htdocs/index.php(83): Mage::run('', '')
#11 {main}";s:3:"url";s:51:"/paymentgateway/gateway/index/method/sofortbanking/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:2:"de";}

```

**Comment by serucee** [comment]
Hi @roman204 ,

thank you for your feedback! This is a known issue and will be fixed in the upcoming release!

Best regards,
Wirecard Shop Systems Team

**Comment by mnentwich** [comment]
As far as i can see the problem occurs when an item is ordered again and multiple items are present in the previous order.

The Method hasReorderedItems in Threeds.php (line 188) builds an sql wich uses the order_id instead of the item_id as unique ID for the collection.

Problematic code:
```
        /** @var Mage_Sales_Model_Resource_Order_Collection $orderCollection */
        $orderCollection = Mage::getModel('sales/order')
            ->getCollection();

        $orderCollection->join(['oi' => 'sales/order_item'], 'oi.order_id = main_table.entity_id');
        $orderCollection->addFieldToFilter('customer_id', $this->getCustomerSession()->getCustomerId());
        $orderCollection->addFieldToFilter('oi.product_id', ['in' => $productIds]);

        return $orderCollection->count() > 0;
```


As a patch you could rewrite the collection Loader to user the sales order_item as unique ID.
```
        /** @var Mage_Sales_Model_Resource_Order_Collection $orderCollection */
        $orderCollection = Mage::getModel('sales/order_item')
            ->getCollection();

        $orderCollection->join(['o' => 'sales/order'], 'main_table.order_id = o.entity_id');
        $orderCollection->addFieldToFilter('customer_id', $this->getCustomerSession()->getCustomerId());
        $orderCollection->addFieldToFilter('main_table.product_id', ['in' => $productIds]);

        return $orderCollection->count() > 0;
```

**Comment by serucee** [comment]
Hi @mnentwich ,

thank you for your investigation, we already have fixed the issue and will soon release it.

Best regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hi @roman204 , @mnentwich 

the latest release (1.3.1) includes the fix for this issue.

Best regards,
Wirecard Shop Systems Team
